name: build-and-push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and Push Coursier
        uses: docker/build-push-action@v2
        with:
          context: ./coursier/
          push: true
          tags: reskin89/scala-coursier-alpine:latest, reskin89/scala-coursier-alpine:0.1.0
    -
      name: Build and Push sbt
      uses: docker/build-push-action@v2
      with:
        context: ./sbt/
        push: true
        tags: reskin89/scala-sbt-alpine:latest, reskin89/scala-sbt-alpine:0.1.0
